component_management:
  default_rules:
    - type: project
      target: 75%
      threshold: 1%
  individual_components:
    - component_id: core
      paths:
        - spring-web-query-core/
    - component_id: starter
      paths:
        - spring-boot-starter-web-query/
comment:
  layout: "condensed_header, diff, flags, components"