coverage:
  status:
    project:
      core:
        flags:
          - core
        target: 75%
        threshold: 1%
        branches:
          - main
      starter:
        flags:
          - starter
        target: 75%
        threshold: 1%
        branches:
          - main

flags:
  core:
    paths:
      - spring-web-query-core/

  starter:
    paths:
      - spring-boot-starter-web-query/

comment:
  layout: " diff, flags, files"