name: Generate JaCoCo Report

on:
    workflow_call:

jobs:
    jacoco:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

            - name: Set up JDK 17
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
              with:
                  distribution: temurin
                  java-version: "17"
                  cache: maven

            - name: Run tests for core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B -ntp clean test -Pjacoco,boot4

            - name: Upload core jacoco report
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
              with:
                  name: spring-web-query-core-jacoco-report
                  path: spring-web-query-core/target/site/jacoco

            - name: Run tests for starter package
              working-directory: ${{ github.workspace }}/spring-boot-starter-web-query
              run: mvn -B -ntp clean test -Pjacoco,boot4

            - name: Upload starter jacoco report
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
              with:
                  name: spring-boot-starter-web-query-jacoco-report
                  path: spring-boot-starter-web-query/target/site/jacoco