name: Publish Javadoc
on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
        steps:
            - name: Setup AWS Credentials
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set region $AWS_REGION

            - name: Trigger Lambda Function
              run: |
                aws lambda invoke \
                --function-name cloudflare_javadoc_deploy_zip \
                --log-type Tail \
                --payload '{"deploymentIds": []}' \
                out \
                --cli-binary-format raw-in-base64-out \
                --query 'LogResult' --output text \
                | base64 --decode