name: Publish Javadoc
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
        steps:
            - name: Setup AWS Credentials
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set region $AWS_REGION

            - name: Trigger Lambda Function
              run: |
                aws lambda invoke \
                --function-name cloudflare_javadoc_deploy \
                --log-type Tail \
                --payload '{
                    "packages": [
                        {
                            "groupId": "in.co.akshitbansal",
                            "artifactId": "spring-web-query-core"
                        },
                    
                        {
                            "groupId": "in.co.akshitbansal",
                            "artifactId": "spring-boot-starter-web-query"
                        }
                    ]
                }' \
                out \
                --cli-binary-format raw-in-base64-out \
                --query 'LogResult' --output text \
                | base64 --decode