name: JMH Benchmarks

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read

jobs:
  in-progress-comment:
    name: In-Progress PR Comment
    if: github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'benchmarks')
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
          -b "📊 Benchmark workflow triggered. JMH benchmarks are currently running against this PR. Please wait while performance measurements are collected."
        env:
          GH_TOKEN: ${{ github.token }}
  jmh:
    name: Run JMH Benchmarks
    if: github.event_name == 'workflow_dispatch' || (github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'benchmarks'))
    runs-on: ubuntu-latest
    strategy:
      matrix:
        className:
          - ReflectiveFieldResolverBenchmark
          - DTOToEntityPathMapperBenchmark
          - CachedDTOToEntityPathMapperBenchmark
          - ListHashingBenchmark
          - PreferredConstructorDiscovererBenchmarkWithGrowingNumberOfConstructorParams
          - PreferredConstructorDiscovererBenchmarkWithGrowingNumberOfConstructors
          - CachedPreferredConstructorDiscovererBenchmarkWithGrowingNumberOfConstructorParams

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build core package
        working-directory: ${{ github.workspace }}/spring-web-query-core
        run: mvn -B -ntp clean install

      - name: Build JMH Maven Project
        working-directory: ${{ github.workspace }}/jmh-benchmarks
        run: mvn -B -ntp clean verify

      - name: Run Benchmarks
        working-directory: ${{ github.workspace }}/jmh-benchmarks/target
        run: java -jar benchmarks.jar "^.*\.${{ matrix.className }}\..*$" -rf json -rff results.json

      - name: Generate summary
        working-directory: ${{ github.workspace }}/jmh-benchmarks/target
        run: |
          {
            echo "# 🚀 ${{ matrix.className }} JMH Benchmarks"
            echo ""
            echo "| Benchmark | Params | Mode | Score | Error | Units |"
            echo "|-----------|--------|------|-------|-------|-------|"

            jq -r '
              .[] |
              "| \(.benchmark) | \(
                  (.params // {})
                  | to_entries
                  | map("\(.key)=\(.value)")
                  | join(", ")
                ) | \(.mode) | \(.primaryMetric.score) | \(.primaryMetric.scoreError // "-") | \(.primaryMetric.scoreUnit) |"
            ' results.json
          } >> report.md

          cat report.md >> $GITHUB_STEP_SUMMARY

      - name: Completed Comment
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
          -F report.md
        env:
          GH_TOKEN: ${{ github.token }}
