name: Java CI

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    security-events: write

jobs:
    build-test:
        runs-on: ubuntu-latest
        if: >-
            ${{ github.event_name != 'push' || !(
              contains(github.event.head_commit.message, 'SKIP CI')
            ) }}
        strategy:
            matrix:
                java-version:
                    - 17
                    - 21
                spring-boot-profile:
                    - boot3
                    - boot4
        name: Build (java${{ matrix.java-version }}, ${{ matrix.spring-boot-profile }})

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

            - name: Set up JDK ${{ matrix.java-version }}
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
              with:
                  distribution: temurin
                  java-version: ${{ matrix.java-version }}
                  cache: maven

            - name: Build core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B -ntp clean install -P${{ matrix.spring-boot-profile }}

            - name: Build spring-boot-starter
              working-directory: ${{ github.workspace }}/spring-boot-starter-web-query
              run: mvn -B -ntp clean verify -P${{ matrix.spring-boot-profile }}

    jmh-build-test:
        runs-on: ubuntu-latest
        if: >-
            ${{ github.event_name != 'push' || !(
              contains(github.event.head_commit.message, 'SKIP CI')
            ) }}
        name: Build JMH Benchmarks

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

            - name: Set up JDK 17
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
              with:
                  distribution: temurin
                  java-version: "17"
                  cache: maven

            - name: Build core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B -ntp clean install

            - name: Build jmh project
              working-directory: ${{ github.workspace }}/jmh-benchmarks
              run: mvn -B -ntp clean verify

    jacoco:
        uses: ./.github/workflows/jacoco.yml
        needs:
            - build-test
            - jmh-build-test
        name: JaCoCo Report Generation

    trivy:
        uses: ./.github/workflows/trivy.yml
        needs:
            - build-test
            - jmh-build-test
        name: Trivy
        with:
            target_branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

    codeql:
        uses: ./.github/workflows/codeql.yml
        needs:
            - build-test
            - jmh-build-test
        name: CodeQL
        with:
            target_branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

    snapshot-release:
        name: Snapshot Release
        needs:
            - build-test
            - jmh-build-test
        runs-on: ubuntu-latest
        if: >-
            ${{ 
                github.event_name == 'push' && 
                !(contains(github.event.head_commit.message, 'SKIP CI'))
            }}

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

            - name: Set up JDK 17
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
              with:
                  distribution: temurin
                  java-version: "17"
                  cache: maven
                  server-id: central
                  server-username: MAVEN_CENTRAL_USERNAME
                  server-password: MAVEN_CENTRAL_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                  gpg-passphrase: GPG_PASSPHRASE

            - name: Release core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B clean deploy -Prelease,boot4 -DskipTests
              env:
                  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

            - name: Release spring-boot-starter
              working-directory: ${{ github.workspace }}/spring-boot-starter-web-query
              run: mvn -B clean deploy -Prelease,boot4 -DskipTests
              env:
                  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    publish-javadoc:
        name: Publish Javadoc
        needs: snapshot-release
        uses: ./.github/workflows/javadoc.yml
        secrets: inherit