name: Java CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-test:
        runs-on: ubuntu-latest
        if: >-
            ${{ github.event_name != 'push' || !(
              contains(github.event.head_commit.message, 'SKIP CI')
            ) }}
        strategy:
            matrix:
                java-version:
                    - 17
                    - 21
                spring-boot-version:
                    - 3.5.12
                    - 4.0.2
        name: Build (Java ${{ matrix.java-version }}, Spring Boot ${{ matrix.spring-boot-version }})

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up JDK ${{ matrix.java-version }}
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: ${{ matrix.java-version }}
                  cache: maven

            - name: Build core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B -ntp clean install -Dspring-boot.version=${{ matrix.spring-boot-version }}

            - name: Build spring-boot-starter
              working-directory: ${{ github.workspace }}/spring-boot-starter-web-query
              run: mvn -B -ntp clean verify -Dspring-boot.version=${{ matrix.spring-boot-version }}

    trivy-scan:
        runs-on: ubuntu-latest
        name: Trivy Scan
        needs: build-test
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.35.0
              with:
                scan-type: 'fs'
                scan-ref: '.'

    snapshot-release:
        name: Snapshot Release
        needs: trivy-scan
        runs-on: ubuntu-latest
        if: >-
            ${{ github.event_name == 'push' && !(
              contains(github.event.head_commit.message, 'SKIP CI')
            ) }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up JDK 17
              uses: actions/setup-java@v5
              with:
                  distribution: temurin
                  java-version: "17"
                  cache: maven
                  server-id: central
                  server-username: MAVEN_CENTRAL_USERNAME
                  server-password: MAVEN_CENTRAL_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                  gpg-passphrase: GPG_PASSPHRASE

            - name: Release core package
              working-directory: ${{ github.workspace }}/spring-web-query-core
              run: mvn -B clean deploy -Prelease -DskipTests
              env:
                  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

            - name: Release spring-boot-starter
              working-directory: ${{ github.workspace }}/spring-boot-starter-web-query
              run: mvn -B clean deploy -Prelease -DskipTests
              env:
                  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    javadoc-deploy:
        name: Javadoc Deploy
        needs: snapshot-release
        runs-on: ubuntu-latest
        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
        steps:
            - name: Setup AWS Credentials
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set region $AWS_REGION

            - name: Trigger Lambda Function
              run: |
                  aws lambda invoke \
                  --function-name cloudflare_javadoc_deploy_zip \
                  --log-type Tail \
                  --payload '{"deploymentIds": []}' \
                  out \
                  --cli-binary-format raw-in-base64-out \
                  --query 'LogResult' --output text \
                  | base64 --decode