name: Trivy Code Scanning

on:
    push:
        branches:
            - main
            - release/**
    pull_request:
    schedule:
        - cron: '0 12 * * *'

permissions:
    security-events: write

jobs:
    trivy-code-scanning:
        runs-on: ubuntu-latest
        name: Trivy Code Scanning
        if: >-
            ${{ github.event_name != 'push' || !(
              contains(github.event.head_commit.message, 'SKIP CI')
            ) }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Run Trivy (generate SARIF)
              uses: aquasecurity/trivy-action@0.35.0
              with:
                scan-type: 'fs'
                scan-ref: '.'
                trivy-config: trivy.yaml
                format: 'sarif'
                output: 'report.sarif'

            - name: Upload results to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v4
              with:
                sarif_file: report.sarif
                category: trivy