name: Trivy Code Scanning

on:
    push:
        branches:
            - main
            - release/**
    pull_request:
    schedule:
        - cron: "0 12 * * *"

permissions:
    security-events: write

jobs:
    trivy-code-scanning:
        runs-on: ubuntu-latest
        name: Trivy Code Scanning

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Run Trivy (table output)
              uses: aquasecurity/trivy-action@0.35.0
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'table'
              env:
                TRIVY_TABLE_MODE: summary

            - name: Run Trivy (generate SARIF)
              uses: aquasecurity/trivy-action@0.35.0
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'sarif'
                output: 'report.sarif'

            - name: Upload results to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v4
              with:
                sarif_file: report.sarif
                category: trivy